FORCE指定したらmaster/develop直pushおｋ

diff --git a/linked/.gittemplate/hooks/pre-push b/linked/.gittemplate/hooks/pre-push
--- a/linked/.gittemplate/hooks/pre-push
+++ b/linked/.gittemplate/hooks/pre-push
@@ -1,4 +1,7 @@
-branch=$(git rev-parse --abbrev-ref HEAD)
-case $branch in
-  "master" | "develop" ) echo "You can't push the ${branch} branch to the remote" && exit 1
-esac
+if [ -z $FORCE ]
+then
+  branch=$(git rev-parse --abbrev-ref HEAD)
+  case $branch in
+    "master" | "develop" ) echo "You can't push the ${branch} branch to the remote" && exit 1
+  esac
+fi
